import { ModelCapability } from '../types.js';

export const MODEL_REGISTRY: ModelCapability[] = [
  {
    id: 'gemini-3.1-flash-lite-image',
    name: 'Gemini Flash Image Lite',
    provider: 'google',
    type: 'image',
    description: 'Fast, high-efficiency image generation and natural language edits with low latency.',
    creditCost: 3,
    creditUnit: 'per image',
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    resolutions: ['1K'],
    supportsReferences: true,
    maxReferences: 2,
    supportsExtension: false,
    supportsTransitions: false,
    isPaidOnly: true,
  },
  {
    id: 'gemini-3.1-flash-image',
    name: 'Gemini Flash Image Studio',
    provider: 'google',
    type: 'image',
    description: 'Flagship image model supporting 512px, 1K, 2K, and 4K outputs with complex creative prompt adhesion.',
    creditCost: 6,
    creditUnit: 'per image',
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '1:4', '4:1'],
    resolutions: ['512px', '1K', '2K', '4K'],
    supportsReferences: true,
    maxReferences: 4,
    supportsExtension: false,
    supportsTransitions: false,
    isPaidOnly: true,
  },
  {
    id: 'veo-3.1-lite-generate-preview',
    name: 'Veo 3.1 Lite',
    provider: 'google',
    type: 'video',
    description: 'Rapid video generation from text prompts and starting frames up to 1080p.',
    creditCost: 18,
    creditUnit: 'per clip (5-7s)',
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p'],
    maxDuration: 8,
    supportsReferences: true,
    maxReferences: 1,
    supportsExtension: false,
    supportsTransitions: true,
    isPaidOnly: true,
  },
  {
    id: 'veo-3.1-generate-preview',
    name: 'Veo 3.1 Pro',
    provider: 'google',
    type: 'video',
    description: 'Cinematic video model supporting 4K resolution, seamless video extensions (+7s), and multi-reference asset steering.',
    creditCost: 32,
    creditUnit: 'per clip (5-7s)',
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p', '4K'],
    maxDuration: 8,
    supportsReferences: true,
    maxReferences: 3,
    supportsExtension: true,
    supportsTransitions: true,
    isPaidOnly: true,
  },
  {
    id: 'kinetix-sequence-orchestrator',
    name: 'Kinetix 30s Sequence Engine',
    provider: 'kinetix-orchestrator',
    type: 'video',
    description: 'Intelligent multi-segment orchestrator stitching up to 30s sequences with continuity preservation across shots.',
    creditCost: 85,
    creditUnit: 'per 30s sequence',
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p'],
    maxDuration: 30,
    supportsReferences: true,
    maxReferences: 5,
    supportsExtension: true,
    supportsTransitions: true,
    isPaidOnly: false,
  },
];
